#!/bin/bash

check=$(cat /etc/selinux/config | grep "SELINUX=permissive" | wc -l)
echo $check

if [ $check -eq  0 ]; then
    if [ $test_only -eq 0 ]; then
        echo "SELINUX=permissive" > /etc/selinux/config
        echo "SELINUXTYPE=targeted" >> /etc/selinux/config
    else
        exit 0
    fi
fi
