#!/bin/bash
#
# Copyright (c) 2015 Mirantis Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#TODO(slukjanov): replace with special image for fake plugin (cloud ubuntu?)
export SAHARA_FAKE_PLUGIN_IMAGE=http://tarballs.openstack.org/heat-test-image/fedora-heat-test-image.qcow2
export SAHARA_FAKE_PLUGIN_IMAGE_NAME=$(basename $SAHARA_FAKE_PLUGIN_IMAGE .qcow2)
export SAHARA_FAKE_PLUGIN_IMAGE_USERNAME=fedora
export SAHARA_FLAVOR_NAME=sahara-flavor
export SAHARA_FLAVOR_ID=20
export SAHARA_FLAVOR_RAM=512
export SAHARA_FLAVOR_DISK=4
export SAHARA_FLAVOR_VCPUS=1
