#!/bin/bash

if [ ! -n /tmp/UnlimitedPolicy/ ]; then
    if [ $test_only -eq 0 ]; then
        mkdir /tmp/UnlimitedPolicy/
        curl -sS $unlimited_security_location/local_policy.jar -o /tmp/UnlimitedPolicy/local_policy.jar
        curl -sS $unlimited_security_location/US_export_policy.jar -o /tmp/UnlimitedPolicy/US_export_policy.jar
    else
        exit 0
    fi
fi
