#!/bin/bash

# Settings needed for the Sahara plugin
# -------------------------------------

# Set up default directories
SAHARACLIENT_DIR=$DEST/python-saharaclient
SAHARA_DIR=$DEST/sahara

SAHARACLIENT_REPO=${SAHARACLIENT_REPO:-\
${GIT_BASE}/openstack/python-saharaclient.git}
SAHARACLIENT_BRANCH=${SAHARACLIENT_BRANCH:-master}

SAHARA_CONF_DIR=${SAHARA_CONF_DIR:-/etc/sahara}
SAHARA_CONF_FILE=${SAHARA_CONF_DIR}/sahara.conf

# TODO(slukjanov): Should we append sahara to SSL_ENABLED_SERVICES?

if is_ssl_enabled_service "sahara" || is_service_enabled tls-proxy; then
    SAHARA_SERVICE_PROTOCOL="https"
fi
SAHARA_SERVICE_HOST=${SAHARA_SERVICE_HOST:-$SERVICE_HOST}
SAHARA_SERVICE_PORT=${SAHARA_SERVICE_PORT:-8386}
SAHARA_SERVICE_PORT_INT=${SAHARA_SERVICE_PORT_INT:-18386}
SAHARA_SERVICE_PROTOCOL=${SAHARA_SERVICE_PROTOCOL:-$SERVICE_PROTOCOL}

SAHARA_AUTH_CACHE_DIR=${SAHARA_AUTH_CACHE_DIR:-/var/cache/sahara}

SAHARA_ENABLED_PLUGINS=${SAHARA_ENABLED_PLUGINS:-\
vanilla,hdp,cdh,mapr,spark,storm,fake}
SAHARA_BIN_DIR=$(get_python_exec_prefix)

SAHARA_ENABLE_DISTRIBUTED_PERIODICS=${SAHARA_ENABLE_DISTRIBUTED_PERIODICS:-\
True}
SAHARA_PERIODIC_COORDINATOR_URL=${SAHARA_PERIODIC_COORDINATOR_URL:-\
kazoo://127.0.0.1:2181}

# Tell Tempest this project is present
TEMPEST_SERVICES+=,sahara

enable_service sahara-api sahara-eng
enable_service heat h-eng h-api h-api-cfn h-api-cw

if [ "$SAHARA_ENABLE_DISTRIBUTED_PERIODICS" == "True" ]; then
    enable_service zookeeper
fi
