#!/bin/bash

register_project_for_upgrade sahara
register_db_to_save sahara
devstack_localrc base IMAGE_URLS=\
"http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-uec.tar.gz,\
http://tarballs.openstack.org/heat-test-image/fedora-heat-test-image.qcow2"
devstack_localrc base enable_plugin sahara \
                                    https://opendev.org/openstack/sahara \
                                    stable/train
devstack_localrc base enable_plugin heat \
                                    https://opendev.org/openstack/heat \
                                    stable/train
devstack_localrc base DEFAULT_IMAGE_NAME="cirros-0.3.5-x86_64-uec"

devstack_localrc target IMAGE_URLS=\
"http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-uec.tar.gz,\
http://tarballs.openstack.org/heat-test-image/fedora-heat-test-image.qcow2"
devstack_localrc target enable_plugin sahara \
                                    https://opendev.org/openstack/sahara
devstack_localrc target enable_plugin heat \
                                    https://opendev.org/openstack/heat
devstack_localrc target LIBS_FROM_GIT=python-saharaclient
devstack_localrc target DEFAULT_IMAGE_NAME="cirros-0.3.5-x86_64-uec"
