#!/bin/bash

register_project_for_upgrade sahara
register_db_to_save sahara
devstack_localrc base disable_service n-net
devstack_localrc base enable_service \
    h-api h-api-cfn h-api-cw h-eng heat \
    q-agt q-dhcp q-l3 q-meta q-svc neutron \
    tempest ceilometer-alarm-evaluator \
    ceilometer-alarm-notifier \
    ceilometer-anotification
devstack_localrc base IMAGE_URLS=\
"http://download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-uec.tar.gz,\
http://tarballs.openstack.org/heat-test-image/fedora-heat-test-image.qcow2"
devstack_localrc base enable_plugin sahara \
                                    git://git.openstack.org/openstack/sahara \
                                    stable/mitaka
devstack_localrc base DEFAULT_IMAGE_NAME="cirros-0.3.2-x86_64-uec"
devstack_localrc target disable_service n-net
devstack_localrc target enable_service \
    h-api h-api-cfn h-api-cw h-eng heat \
    q-agt q-dhcp q-l3 q-meta q-svc neutron \
    tempest ceilometer-alarm-evaluator \
    ceilometer-alarm-notifier \
    ceilometer-anotification
devstack_localrc target IMAGE_URLS=\
"http://download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-uec.tar.gz,\
http://tarballs.openstack.org/heat-test-image/fedora-heat-test-image.qcow2"
devstack_localrc target enable_plugin sahara \
                                    git://git.openstack.org/openstack/sahara
devstack_localrc target LIBS_FROM_GIT=python-saharaclient
devstack_localrc target DEFAULT_IMAGE_NAME="cirros-0.3.2-x86_64-uec"
