#!/bin/bash -e

echo "Building docs..."

rm -rf doc/html doc/build
rm -rf doc/source/apidoc doc/source/api

.venv/bin/python setup.py build_sphinx

echo "Done."
echo "Docs are now available in 'doc/build/html/'"
